package utilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// PublicIPListReader is a Reader for the PublicIPList structure.
type PublicIPListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PublicIPListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPublicIPListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPublicIPListOK creates a PublicIPListOK with default headers values
func NewPublicIPListOK() *PublicIPListOK {
	return &PublicIPListOK{}
}

/*PublicIPListOK handles this case with default header values.

Successful response
*/
type PublicIPListOK struct {
	Payload *models.PublicIPList
}

func (o *PublicIPListOK) Error() string {
	return fmt.Sprintf("[GET /public-ip-list][%d] publicIpListOK  %+v", 200, o.Payload)
}

func (o *PublicIPListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PublicIPList)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
