package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCreateTokenParams creates a new CreateTokenParams object
// with the default values initialized.
func NewCreateTokenParams() *CreateTokenParams {
	var ()
	return &CreateTokenParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateTokenParamsWithTimeout creates a new CreateTokenParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateTokenParamsWithTimeout(timeout time.Duration) *CreateTokenParams {
	var ()
	return &CreateTokenParams{

		timeout: timeout,
	}
}

// NewCreateTokenParamsWithContext creates a new CreateTokenParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateTokenParamsWithContext(ctx context.Context) *CreateTokenParams {
	var ()
	return &CreateTokenParams{

		Context: ctx,
	}
}

/*CreateTokenParams contains all the parameters to send to the API endpoint
for the create token operation typically these are written to a http.Request
*/
type CreateTokenParams struct {

	/*FASTLYOTP
	  2FA OTP for enabled accounts

	*/
	FASTLYOTP *string
	/*Name
	  Name of the Token

	*/
	Name *string
	/*Password
	  Password of the authorized user

	*/
	Password strfmt.Password
	/*Username
	  Username of the authorized user

	*/
	Username string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create token params
func (o *CreateTokenParams) WithTimeout(timeout time.Duration) *CreateTokenParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create token params
func (o *CreateTokenParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create token params
func (o *CreateTokenParams) WithContext(ctx context.Context) *CreateTokenParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create token params
func (o *CreateTokenParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithFASTLYOTP adds the fASTLYOTP to the create token params
func (o *CreateTokenParams) WithFASTLYOTP(fASTLYOTP *string) *CreateTokenParams {
	o.SetFASTLYOTP(fASTLYOTP)
	return o
}

// SetFASTLYOTP adds the fASTLYOTP to the create token params
func (o *CreateTokenParams) SetFASTLYOTP(fASTLYOTP *string) {
	o.FASTLYOTP = fASTLYOTP
}

// WithName adds the name to the create token params
func (o *CreateTokenParams) WithName(name *string) *CreateTokenParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the create token params
func (o *CreateTokenParams) SetName(name *string) {
	o.Name = name
}

// WithPassword adds the password to the create token params
func (o *CreateTokenParams) WithPassword(password strfmt.Password) *CreateTokenParams {
	o.SetPassword(password)
	return o
}

// SetPassword adds the password to the create token params
func (o *CreateTokenParams) SetPassword(password strfmt.Password) {
	o.Password = password
}

// WithUsername adds the username to the create token params
func (o *CreateTokenParams) WithUsername(username string) *CreateTokenParams {
	o.SetUsername(username)
	return o
}

// SetUsername adds the username to the create token params
func (o *CreateTokenParams) SetUsername(username string) {
	o.Username = username
}

// WriteToRequest writes these params to a swagger request
func (o *CreateTokenParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.FASTLYOTP != nil {

		// header param FASTLY_OTP
		if err := r.SetHeaderParam("FASTLY_OTP", *o.FASTLYOTP); err != nil {
			return err
		}

	}

	if o.Name != nil {

		// form param name
		var frName string
		if o.Name != nil {
			frName = *o.Name
		}
		fName := frName
		if fName != "" {
			if err := r.SetFormParam("name", fName); err != nil {
				return err
			}
		}

	}

	// form param password
	frPassword := o.Password
	fPassword := frPassword.String()
	if fPassword != "" {
		if err := r.SetFormParam("password", fPassword); err != nil {
			return err
		}
	}

	// form param username
	frUsername := o.Username
	fUsername := frUsername
	if fUsername != "" {
		if err := r.SetFormParam("username", fUsername); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
