package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// TokensDeleteReader is a Reader for the TokensDelete structure.
type TokensDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *TokensDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewTokensDeleteNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewTokensDeleteNoContent creates a TokensDeleteNoContent with default headers values
func NewTokensDeleteNoContent() *TokensDeleteNoContent {
	return &TokensDeleteNoContent{}
}

/*TokensDeleteNoContent handles this case with default header values.

Token deleted
*/
type TokensDeleteNoContent struct {
	Payload string
}

func (o *TokensDeleteNoContent) Error() string {
	return fmt.Sprintf("[DELETE /tokens/{tokenId}][%d] tokensDeleteNoContent  %+v", 204, o.Payload)
}

func (o *TokensDeleteNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
