package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewTokensDeleteParams creates a new TokensDeleteParams object
// with the default values initialized.
func NewTokensDeleteParams() *TokensDeleteParams {
	var ()
	return &TokensDeleteParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTokensDeleteParamsWithTimeout creates a new TokensDeleteParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTokensDeleteParamsWithTimeout(timeout time.Duration) *TokensDeleteParams {
	var ()
	return &TokensDeleteParams{

		timeout: timeout,
	}
}

// NewTokensDeleteParamsWithContext creates a new TokensDeleteParams object
// with the default values initialized, and the ability to set a context for a request
func NewTokensDeleteParamsWithContext(ctx context.Context) *TokensDeleteParams {
	var ()
	return &TokensDeleteParams{

		Context: ctx,
	}
}

/*TokensDeleteParams contains all the parameters to send to the API endpoint
for the tokens delete operation typically these are written to a http.Request
*/
type TokensDeleteParams struct {

	/*TokenID
	  Id of token to delete

	*/
	TokenID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tokens delete params
func (o *TokensDeleteParams) WithTimeout(timeout time.Duration) *TokensDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tokens delete params
func (o *TokensDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tokens delete params
func (o *TokensDeleteParams) WithContext(ctx context.Context) *TokensDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tokens delete params
func (o *TokensDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithTokenID adds the tokenID to the tokens delete params
func (o *TokensDeleteParams) WithTokenID(tokenID string) *TokensDeleteParams {
	o.SetTokenID(tokenID)
	return o
}

// SetTokenID adds the tokenId to the tokens delete params
func (o *TokensDeleteParams) SetTokenID(tokenID string) {
	o.TokenID = tokenID
}

// WriteToRequest writes these params to a swagger request
func (o *TokensDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param tokenId
	if err := r.SetPathParam("tokenId", o.TokenID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
