package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// CreateFeatureReader is a Reader for the CreateFeature structure.
type CreateFeatureReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateFeatureReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCreateFeatureOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateFeatureOK creates a CreateFeatureOK with default headers values
func NewCreateFeatureOK() *CreateFeatureOK {
	return &CreateFeatureOK{}
}

/*CreateFeatureOK handles this case with default header values.

Successful response
*/
type CreateFeatureOK struct {
	Payload *models.FeatureCreateBody
}

func (o *CreateFeatureOK) Error() string {
	return fmt.Sprintf("[POST /features][%d] createFeatureOK  %+v", 200, o.Payload)
}

func (o *CreateFeatureOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.FeatureCreateBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
