package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// NewCreateFeatureParams creates a new CreateFeatureParams object
// with the default values initialized.
func NewCreateFeatureParams() *CreateFeatureParams {
	var ()
	return &CreateFeatureParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateFeatureParamsWithTimeout creates a new CreateFeatureParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateFeatureParamsWithTimeout(timeout time.Duration) *CreateFeatureParams {
	var ()
	return &CreateFeatureParams{

		timeout: timeout,
	}
}

// NewCreateFeatureParamsWithContext creates a new CreateFeatureParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateFeatureParamsWithContext(ctx context.Context) *CreateFeatureParams {
	var ()
	return &CreateFeatureParams{

		Context: ctx,
	}
}

/*CreateFeatureParams contains all the parameters to send to the API endpoint
for the create feature operation typically these are written to a http.Request
*/
type CreateFeatureParams struct {

	/*Data
	  The feature to be created

	*/
	Data *models.FeatureCreateBody

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create feature params
func (o *CreateFeatureParams) WithTimeout(timeout time.Duration) *CreateFeatureParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create feature params
func (o *CreateFeatureParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create feature params
func (o *CreateFeatureParams) WithContext(ctx context.Context) *CreateFeatureParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create feature params
func (o *CreateFeatureParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithData adds the data to the create feature params
func (o *CreateFeatureParams) WithData(data *models.FeatureCreateBody) *CreateFeatureParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create feature params
func (o *CreateFeatureParams) SetData(data *models.FeatureCreateBody) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *CreateFeatureParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.Data == nil {
		o.Data = new(models.FeatureCreateBody)
	}

	if err := r.SetBodyParam(o.Data); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
