package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// CurrentCustomerReader is a Reader for the CurrentCustomer structure.
type CurrentCustomerReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CurrentCustomerReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCurrentCustomerOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCurrentCustomerOK creates a CurrentCustomerOK with default headers values
func NewCurrentCustomerOK() *CurrentCustomerOK {
	return &CurrentCustomerOK{}
}

/*CurrentCustomerOK handles this case with default header values.

Successful response
*/
type CurrentCustomerOK struct {
	Payload *models.Customer
}

func (o *CurrentCustomerOK) Error() string {
	return fmt.Sprintf("[GET /current_customer][%d] currentCustomerOK  %+v", 200, o.Payload)
}

func (o *CurrentCustomerOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Customer)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
