package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCurrentCustomerParams creates a new CurrentCustomerParams object
// with the default values initialized.
func NewCurrentCustomerParams() *CurrentCustomerParams {

	return &CurrentCustomerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCurrentCustomerParamsWithTimeout creates a new CurrentCustomerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCurrentCustomerParamsWithTimeout(timeout time.Duration) *CurrentCustomerParams {

	return &CurrentCustomerParams{

		timeout: timeout,
	}
}

// NewCurrentCustomerParamsWithContext creates a new CurrentCustomerParams object
// with the default values initialized, and the ability to set a context for a request
func NewCurrentCustomerParamsWithContext(ctx context.Context) *CurrentCustomerParams {

	return &CurrentCustomerParams{

		Context: ctx,
	}
}

/*CurrentCustomerParams contains all the parameters to send to the API endpoint
for the current customer operation typically these are written to a http.Request
*/
type CurrentCustomerParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the current customer params
func (o *CurrentCustomerParams) WithTimeout(timeout time.Duration) *CurrentCustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the current customer params
func (o *CurrentCustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the current customer params
func (o *CurrentCustomerParams) WithContext(ctx context.Context) *CurrentCustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the current customer params
func (o *CurrentCustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *CurrentCustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
