package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerUsersParams creates a new CustomerUsersParams object
// with the default values initialized.
func NewCustomerUsersParams() *CustomerUsersParams {
	var ()
	return &CustomerUsersParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerUsersParamsWithTimeout creates a new CustomerUsersParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerUsersParamsWithTimeout(timeout time.Duration) *CustomerUsersParams {
	var ()
	return &CustomerUsersParams{

		timeout: timeout,
	}
}

// NewCustomerUsersParamsWithContext creates a new CustomerUsersParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerUsersParamsWithContext(ctx context.Context) *CustomerUsersParams {
	var ()
	return &CustomerUsersParams{

		Context: ctx,
	}
}

/*CustomerUsersParams contains all the parameters to send to the API endpoint
for the customer users operation typically these are written to a http.Request
*/
type CustomerUsersParams struct {

	/*ID
	  ID of the customer

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer users params
func (o *CustomerUsersParams) WithTimeout(timeout time.Duration) *CustomerUsersParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer users params
func (o *CustomerUsersParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer users params
func (o *CustomerUsersParams) WithContext(ctx context.Context) *CustomerUsersParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer users params
func (o *CustomerUsersParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the customer users params
func (o *CustomerUsersParams) WithID(id string) *CustomerUsersParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer users params
func (o *CustomerUsersParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerUsersParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
