package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewCustomerParams creates a new CustomerParams object
// with the default values initialized.
func NewCustomerParams() *CustomerParams {
	var ()
	return &CustomerParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewCustomerParamsWithTimeout creates a new CustomerParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCustomerParamsWithTimeout(timeout time.Duration) *CustomerParams {
	var ()
	return &CustomerParams{

		timeout: timeout,
	}
}

// NewCustomerParamsWithContext creates a new CustomerParams object
// with the default values initialized, and the ability to set a context for a request
func NewCustomerParamsWithContext(ctx context.Context) *CustomerParams {
	var ()
	return &CustomerParams{

		Context: ctx,
	}
}

/*CustomerParams contains all the parameters to send to the API endpoint
for the customer operation typically these are written to a http.Request
*/
type CustomerParams struct {

	/*ID
	  ID of the customer

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the customer params
func (o *CustomerParams) WithTimeout(timeout time.Duration) *CustomerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the customer params
func (o *CustomerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the customer params
func (o *CustomerParams) WithContext(ctx context.Context) *CustomerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the customer params
func (o *CustomerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the customer params
func (o *CustomerParams) WithID(id string) *CustomerParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the customer params
func (o *CustomerParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *CustomerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
