package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// CustomerUsersReader is a Reader for the CustomerUsers structure.
type CustomerUsersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CustomerUsersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewCustomerUsersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCustomerUsersOK creates a CustomerUsersOK with default headers values
func NewCustomerUsersOK() *CustomerUsersOK {
	return &CustomerUsersOK{}
}

/*CustomerUsersOK handles this case with default header values.

Successful response
*/
type CustomerUsersOK struct {
	Payload []*models.User
}

func (o *CustomerUsersOK) Error() string {
	return fmt.Sprintf("[GET /customer/{id}/users][%d] customerUsersOK  %+v", 200, o.Payload)
}

func (o *CustomerUsersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
