package account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListEventsParams creates a new ListEventsParams object
// with the default values initialized.
func NewListEventsParams() *ListEventsParams {
	var ()
	return &ListEventsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListEventsParamsWithTimeout creates a new ListEventsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListEventsParamsWithTimeout(timeout time.Duration) *ListEventsParams {
	var ()
	return &ListEventsParams{

		timeout: timeout,
	}
}

// NewListEventsParamsWithContext creates a new ListEventsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListEventsParamsWithContext(ctx context.Context) *ListEventsParams {
	var ()
	return &ListEventsParams{

		Context: ctx,
	}
}

/*ListEventsParams contains all the parameters to send to the API endpoint
for the list events operation typically these are written to a http.Request
*/
type ListEventsParams struct {

	/*FilterCustomerID
	  Filter by customer_id

	*/
	FilterCustomerID *string
	/*FilterEventType
	  Filter by event_type

	*/
	FilterEventType *string
	/*FilterServiceID
	  Filter by service_id

	*/
	FilterServiceID *string
	/*FilterUserID
	  Filter by user_id

	*/
	FilterUserID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list events params
func (o *ListEventsParams) WithTimeout(timeout time.Duration) *ListEventsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list events params
func (o *ListEventsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list events params
func (o *ListEventsParams) WithContext(ctx context.Context) *ListEventsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list events params
func (o *ListEventsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithFilterCustomerID adds the filterCustomerID to the list events params
func (o *ListEventsParams) WithFilterCustomerID(filterCustomerID *string) *ListEventsParams {
	o.SetFilterCustomerID(filterCustomerID)
	return o
}

// SetFilterCustomerID adds the filterCustomerId to the list events params
func (o *ListEventsParams) SetFilterCustomerID(filterCustomerID *string) {
	o.FilterCustomerID = filterCustomerID
}

// WithFilterEventType adds the filterEventType to the list events params
func (o *ListEventsParams) WithFilterEventType(filterEventType *string) *ListEventsParams {
	o.SetFilterEventType(filterEventType)
	return o
}

// SetFilterEventType adds the filterEventType to the list events params
func (o *ListEventsParams) SetFilterEventType(filterEventType *string) {
	o.FilterEventType = filterEventType
}

// WithFilterServiceID adds the filterServiceID to the list events params
func (o *ListEventsParams) WithFilterServiceID(filterServiceID *string) *ListEventsParams {
	o.SetFilterServiceID(filterServiceID)
	return o
}

// SetFilterServiceID adds the filterServiceId to the list events params
func (o *ListEventsParams) SetFilterServiceID(filterServiceID *string) {
	o.FilterServiceID = filterServiceID
}

// WithFilterUserID adds the filterUserID to the list events params
func (o *ListEventsParams) WithFilterUserID(filterUserID *string) *ListEventsParams {
	o.SetFilterUserID(filterUserID)
	return o
}

// SetFilterUserID adds the filterUserId to the list events params
func (o *ListEventsParams) SetFilterUserID(filterUserID *string) {
	o.FilterUserID = filterUserID
}

// WriteToRequest writes these params to a swagger request
func (o *ListEventsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.FilterCustomerID != nil {

		// query param filter[customer_id]
		var qrFilterCustomerID string
		if o.FilterCustomerID != nil {
			qrFilterCustomerID = *o.FilterCustomerID
		}
		qFilterCustomerID := qrFilterCustomerID
		if qFilterCustomerID != "" {
			if err := r.SetQueryParam("filter[customer_id]", qFilterCustomerID); err != nil {
				return err
			}
		}

	}

	if o.FilterEventType != nil {

		// query param filter[event_type]
		var qrFilterEventType string
		if o.FilterEventType != nil {
			qrFilterEventType = *o.FilterEventType
		}
		qFilterEventType := qrFilterEventType
		if qFilterEventType != "" {
			if err := r.SetQueryParam("filter[event_type]", qFilterEventType); err != nil {
				return err
			}
		}

	}

	if o.FilterServiceID != nil {

		// query param filter[service_id]
		var qrFilterServiceID string
		if o.FilterServiceID != nil {
			qrFilterServiceID = *o.FilterServiceID
		}
		qFilterServiceID := qrFilterServiceID
		if qFilterServiceID != "" {
			if err := r.SetQueryParam("filter[service_id]", qFilterServiceID); err != nil {
				return err
			}
		}

	}

	if o.FilterUserID != nil {

		// query param filter[user_id]
		var qrFilterUserID string
		if o.FilterUserID != nil {
			qrFilterUserID = *o.FilterUserID
		}
		qFilterUserID := qrFilterUserID
		if qFilterUserID != "" {
			if err := r.SetQueryParam("filter[user_id]", qFilterUserID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
