package purge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// PurgeAllReader is a Reader for the PurgeAll structure.
type PurgeAllReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PurgeAllReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPurgeAllOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPurgeAllOK creates a PurgeAllOK with default headers values
func NewPurgeAllOK() *PurgeAllOK {
	return &PurgeAllOK{}
}

/*PurgeAllOK handles this case with default header values.

Successful response
*/
type PurgeAllOK struct {
	Payload PurgeAllOKBody
}

func (o *PurgeAllOK) Error() string {
	return fmt.Sprintf("[POST /service/{serviceId}/purge_all][%d] purgeAllOK  %+v", 200, o.Payload)
}

func (o *PurgeAllOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PurgeAllOKBody purge all o k body
swagger:model PurgeAllOKBody
*/
type PurgeAllOKBody interface{}
