package purge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPurgeAllParams creates a new PurgeAllParams object
// with the default values initialized.
func NewPurgeAllParams() *PurgeAllParams {
	var ()
	return &PurgeAllParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPurgeAllParamsWithTimeout creates a new PurgeAllParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPurgeAllParamsWithTimeout(timeout time.Duration) *PurgeAllParams {
	var ()
	return &PurgeAllParams{

		timeout: timeout,
	}
}

// NewPurgeAllParamsWithContext creates a new PurgeAllParams object
// with the default values initialized, and the ability to set a context for a request
func NewPurgeAllParamsWithContext(ctx context.Context) *PurgeAllParams {
	var ()
	return &PurgeAllParams{

		Context: ctx,
	}
}

/*PurgeAllParams contains all the parameters to send to the API endpoint
for the purge all operation typically these are written to a http.Request
*/
type PurgeAllParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the purge all params
func (o *PurgeAllParams) WithTimeout(timeout time.Duration) *PurgeAllParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the purge all params
func (o *PurgeAllParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the purge all params
func (o *PurgeAllParams) WithContext(ctx context.Context) *PurgeAllParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the purge all params
func (o *PurgeAllParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the purge all params
func (o *PurgeAllParams) WithServiceID(serviceID string) *PurgeAllParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the purge all params
func (o *PurgeAllParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *PurgeAllParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
