package purge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new purge API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for purge API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
PurgeAll Purges everything for a given service

*/
func (a *Client) PurgeAll(params *PurgeAllParams, authInfo runtime.ClientAuthInfoWriter) (*PurgeAllOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewPurgeAllParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "purge_all",
		Method:             "POST",
		PathPattern:        "/service/{serviceId}/purge_all",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &PurgeAllReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*PurgeAllOK), nil

}

/*
ServiceCreateVersion Create a version for a particular service.

*/
func (a *Client) ServiceCreateVersion(params *ServiceCreateVersionParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceCreateVersionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceCreateVersionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service_create_version",
		Method:             "POST",
		PathPattern:        "/service/{serviceId}/version",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServiceCreateVersionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceCreateVersionOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
