package purge

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServiceCreateVersionParams creates a new ServiceCreateVersionParams object
// with the default values initialized.
func NewServiceCreateVersionParams() *ServiceCreateVersionParams {
	var ()
	return &ServiceCreateVersionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceCreateVersionParamsWithTimeout creates a new ServiceCreateVersionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceCreateVersionParamsWithTimeout(timeout time.Duration) *ServiceCreateVersionParams {
	var ()
	return &ServiceCreateVersionParams{

		timeout: timeout,
	}
}

// NewServiceCreateVersionParamsWithContext creates a new ServiceCreateVersionParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceCreateVersionParamsWithContext(ctx context.Context) *ServiceCreateVersionParams {
	var ()
	return &ServiceCreateVersionParams{

		Context: ctx,
	}
}

/*ServiceCreateVersionParams contains all the parameters to send to the API endpoint
for the service create version operation typically these are written to a http.Request
*/
type ServiceCreateVersionParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service create version params
func (o *ServiceCreateVersionParams) WithTimeout(timeout time.Duration) *ServiceCreateVersionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service create version params
func (o *ServiceCreateVersionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service create version params
func (o *ServiceCreateVersionParams) WithContext(ctx context.Context) *ServiceCreateVersionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service create version params
func (o *ServiceCreateVersionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the service create version params
func (o *ServiceCreateVersionParams) WithServiceID(serviceID string) *ServiceCreateVersionParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the service create version params
func (o *ServiceCreateVersionParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceCreateVersionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
