package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// VersionActivateReader is a Reader for the VersionActivate structure.
type VersionActivateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionActivateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVersionActivateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVersionActivateOK creates a VersionActivateOK with default headers values
func NewVersionActivateOK() *VersionActivateOK {
	return &VersionActivateOK{}
}

/*VersionActivateOK handles this case with default header values.

Successful response
*/
type VersionActivateOK struct {
	Payload *models.Version
}

func (o *VersionActivateOK) Error() string {
	return fmt.Sprintf("[PUT /service/{serviceId}/version/{versionId}/activate][%d] versionActivateOK  %+v", 200, o.Payload)
}

func (o *VersionActivateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Version)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
