package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new version API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for version API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
VersionActivate Activate the current version.

*/
func (a *Client) VersionActivate(params *VersionActivateParams, authInfo runtime.ClientAuthInfoWriter) (*VersionActivateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionActivateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "version_activate",
		Method:             "PUT",
		PathPattern:        "/service/{serviceId}/version/{versionId}/activate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VersionActivateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*VersionActivateOK), nil

}

/*
VersionClone Clone the current configuration into a new version.

*/
func (a *Client) VersionClone(params *VersionCloneParams, authInfo runtime.ClientAuthInfoWriter) (*VersionCloneOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionCloneParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "version_clone",
		Method:             "PUT",
		PathPattern:        "/service/{serviceId}/version/{versionId}/clone",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VersionCloneReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*VersionCloneOK), nil

}

/*
VersionDeactivate Deactivate the current version.

*/
func (a *Client) VersionDeactivate(params *VersionDeactivateParams, authInfo runtime.ClientAuthInfoWriter) (*VersionDeactivateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionDeactivateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "version_deactivate",
		Method:             "PUT",
		PathPattern:        "/service/{serviceId}/version/{versionId}/deactivate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VersionDeactivateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*VersionDeactivateOK), nil

}

/*
VersionGet Get the version for a particular service.

*/
func (a *Client) VersionGet(params *VersionGetParams, authInfo runtime.ClientAuthInfoWriter) (*VersionGetOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionGetParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "version_get",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VersionGetReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*VersionGetOK), nil

}

/*
VersionValidate Validate the version for a particular service and version.

*/
func (a *Client) VersionValidate(params *VersionValidateParams, authInfo runtime.ClientAuthInfoWriter) (*VersionValidateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewVersionValidateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "version_validate",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}/validate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &VersionValidateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*VersionValidateOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
