package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVersionValidateParams creates a new VersionValidateParams object
// with the default values initialized.
func NewVersionValidateParams() *VersionValidateParams {
	var ()
	return &VersionValidateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVersionValidateParamsWithTimeout creates a new VersionValidateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVersionValidateParamsWithTimeout(timeout time.Duration) *VersionValidateParams {
	var ()
	return &VersionValidateParams{

		timeout: timeout,
	}
}

// NewVersionValidateParamsWithContext creates a new VersionValidateParams object
// with the default values initialized, and the ability to set a context for a request
func NewVersionValidateParamsWithContext(ctx context.Context) *VersionValidateParams {
	var ()
	return &VersionValidateParams{

		Context: ctx,
	}
}

/*VersionValidateParams contains all the parameters to send to the API endpoint
for the version validate operation typically these are written to a http.Request
*/
type VersionValidateParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the version validate params
func (o *VersionValidateParams) WithTimeout(timeout time.Duration) *VersionValidateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the version validate params
func (o *VersionValidateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the version validate params
func (o *VersionValidateParams) WithContext(ctx context.Context) *VersionValidateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the version validate params
func (o *VersionValidateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the version validate params
func (o *VersionValidateParams) WithServiceID(serviceID string) *VersionValidateParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the version validate params
func (o *VersionValidateParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the version validate params
func (o *VersionValidateParams) WithVersionID(versionID string) *VersionValidateParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the version validate params
func (o *VersionValidateParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *VersionValidateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
