package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewVersionDeactivateParams creates a new VersionDeactivateParams object
// with the default values initialized.
func NewVersionDeactivateParams() *VersionDeactivateParams {
	var ()
	return &VersionDeactivateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewVersionDeactivateParamsWithTimeout creates a new VersionDeactivateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewVersionDeactivateParamsWithTimeout(timeout time.Duration) *VersionDeactivateParams {
	var ()
	return &VersionDeactivateParams{

		timeout: timeout,
	}
}

// NewVersionDeactivateParamsWithContext creates a new VersionDeactivateParams object
// with the default values initialized, and the ability to set a context for a request
func NewVersionDeactivateParamsWithContext(ctx context.Context) *VersionDeactivateParams {
	var ()
	return &VersionDeactivateParams{

		Context: ctx,
	}
}

/*VersionDeactivateParams contains all the parameters to send to the API endpoint
for the version deactivate operation typically these are written to a http.Request
*/
type VersionDeactivateParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the version deactivate params
func (o *VersionDeactivateParams) WithTimeout(timeout time.Duration) *VersionDeactivateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the version deactivate params
func (o *VersionDeactivateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the version deactivate params
func (o *VersionDeactivateParams) WithContext(ctx context.Context) *VersionDeactivateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the version deactivate params
func (o *VersionDeactivateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the version deactivate params
func (o *VersionDeactivateParams) WithServiceID(serviceID string) *VersionDeactivateParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the version deactivate params
func (o *VersionDeactivateParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the version deactivate params
func (o *VersionDeactivateParams) WithVersionID(versionID string) *VersionDeactivateParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the version deactivate params
func (o *VersionDeactivateParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *VersionDeactivateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
