package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// VersionValidateReader is a Reader for the VersionValidate structure.
type VersionValidateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionValidateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVersionValidateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVersionValidateOK creates a VersionValidateOK with default headers values
func NewVersionValidateOK() *VersionValidateOK {
	return &VersionValidateOK{}
}

/*VersionValidateOK handles this case with default header values.

Successful response
*/
type VersionValidateOK struct {
	Payload VersionValidateOKBody
}

func (o *VersionValidateOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version/{versionId}/validate][%d] versionValidateOK  %+v", 200, o.Payload)
}

func (o *VersionValidateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*VersionValidateOKBody version validate o k body
swagger:model VersionValidateOKBody
*/
type VersionValidateOKBody interface{}
