package version

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// VersionCloneReader is a Reader for the VersionClone structure.
type VersionCloneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *VersionCloneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewVersionCloneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewVersionCloneOK creates a VersionCloneOK with default headers values
func NewVersionCloneOK() *VersionCloneOK {
	return &VersionCloneOK{}
}

/*VersionCloneOK handles this case with default header values.

Successful response
*/
type VersionCloneOK struct {
	Payload *models.Version
}

func (o *VersionCloneOK) Error() string {
	return fmt.Sprintf("[PUT /service/{serviceId}/version/{versionId}/clone][%d] versionCloneOK  %+v", 200, o.Payload)
}

func (o *VersionCloneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Version)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
