package client

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	httptransport "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/client/account"
	"github.com/fastly/openapi/clients/go/client/authentication"
	"github.com/fastly/openapi/clients/go/client/configuration"
	"github.com/fastly/openapi/clients/go/client/purge"
	"github.com/fastly/openapi/clients/go/client/utilities"
	"github.com/fastly/openapi/clients/go/client/version"
)

// Default fastly go client HTTP client.
var Default = NewHTTPClient(nil)

// NewHTTPClient creates a new fastly go client HTTP client.
func NewHTTPClient(formats strfmt.Registry) *FastlyGoClient {
	if formats == nil {
		formats = strfmt.Default
	}
	transport := httptransport.New("api.fastly.com", "/", []string{"https"})
	return New(transport, formats)
}

// New creates a new fastly go client client
func New(transport runtime.ClientTransport, formats strfmt.Registry) *FastlyGoClient {
	cli := new(FastlyGoClient)
	cli.Transport = transport

	cli.Account = account.New(transport, formats)

	cli.Authentication = authentication.New(transport, formats)

	cli.Configuration = configuration.New(transport, formats)

	cli.Purge = purge.New(transport, formats)

	cli.Utilities = utilities.New(transport, formats)

	cli.Version = version.New(transport, formats)

	return cli
}

// FastlyGoClient is a client for fastly go client
type FastlyGoClient struct {
	Account *account.Client

	Authentication *authentication.Client

	Configuration *configuration.Client

	Purge *purge.Client

	Utilities *utilities.Client

	Version *version.Client

	Transport runtime.ClientTransport
}

// SetTransport changes the transport on the client and all its subresources
func (c *FastlyGoClient) SetTransport(transport runtime.ClientTransport) {
	c.Transport = transport

	c.Account.SetTransport(transport)

	c.Authentication.SetTransport(transport)

	c.Configuration.SetTransport(transport)

	c.Purge.SetTransport(transport)

	c.Utilities.SetTransport(transport)

	c.Version.SetTransport(transport)

}
