package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// New creates a new configuration API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) *Client {
	return &Client{transport: transport, formats: formats}
}

/*
Client for configuration API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

/*
GetDomains Returns a list of domains in JSON-API format

*/
func (a *Client) GetDomains(params *GetDomainsParams, authInfo runtime.ClientAuthInfoWriter) (*GetDomainsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetDomainsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetDomains",
		Method:             "GET",
		PathPattern:        "/domains",
		ProducesMediaTypes: []string{"application/vnd.api+json"},
		ConsumesMediaTypes: []string{"application/vnd.api+json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetDomainsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetDomainsOK), nil

}

/*
GetServices Returns a list of services in JSON-API format

*/
func (a *Client) GetServices(params *GetServicesParams, authInfo runtime.ClientAuthInfoWriter) (*GetServicesOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetServicesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "GetServices",
		Method:             "GET",
		PathPattern:        "/services",
		ProducesMediaTypes: []string{"application/vnd.api+json"},
		ConsumesMediaTypes: []string{"application/vnd.api+json"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetServicesReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetServicesOK), nil

}

/*
DeleteCondition Delete a condition for a particular service, version and name

*/
func (a *Client) DeleteCondition(params *DeleteConditionParams, authInfo runtime.ClientAuthInfoWriter) (*DeleteConditionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewDeleteConditionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "delete_condition",
		Method:             "DELETE",
		PathPattern:        "/service/{serviceId}/version/{versionId}/condition/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &DeleteConditionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*DeleteConditionOK), nil

}

/*
GetCondition Display a condition for a particular service, version and name

*/
func (a *Client) GetCondition(params *GetConditionParams, authInfo runtime.ClientAuthInfoWriter) (*GetConditionOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewGetConditionParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "get_condition",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}/condition/{name}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &GetConditionReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*GetConditionOK), nil

}

/*
ListConditions Display conditions for a particular service and version

*/
func (a *Client) ListConditions(params *ListConditionsParams, authInfo runtime.ClientAuthInfoWriter) (*ListConditionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewListConditionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "list_conditions",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}/condition",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ListConditionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ListConditionsOK), nil

}

/*
ServiceVersionBoilerplate Return boilerplate VCL with the service's TTL from the settings.

*/
func (a *Client) ServiceVersionBoilerplate(params *ServiceVersionBoilerplateParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceVersionBoilerplateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceVersionBoilerplateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service_version_boilerplate",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}/boilerplate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServiceVersionBoilerplateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceVersionBoilerplateOK), nil

}

/*
ServiceVersionGeneratedVcl Display the generated VCL for a particular service and version

*/
func (a *Client) ServiceVersionGeneratedVcl(params *ServiceVersionGeneratedVclParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceVersionGeneratedVclOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceVersionGeneratedVclParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service_version_generated_vcl",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}/generated_vcl",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServiceVersionGeneratedVclReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceVersionGeneratedVclOK), nil

}

/*
ServiceVersionVcls List the uploaded VCLs for a particular service and version

*/
func (a *Client) ServiceVersionVcls(params *ServiceVersionVclsParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceVersionVclsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceVersionVclsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service_version_vcls",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version/{versionId}/vcl",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServiceVersionVclsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceVersionVclsOK), nil

}

/*
ServiceVersions List the versions for a particular service.

*/
func (a *Client) ServiceVersions(params *ServiceVersionsParams, authInfo runtime.ClientAuthInfoWriter) (*ServiceVersionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewServiceVersionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "service_versions",
		Method:             "GET",
		PathPattern:        "/service/{serviceId}/version",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &ServiceVersionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*ServiceVersionsOK), nil

}

/*
Stats Returns stats for all regions by service

*/
func (a *Client) Stats(params *StatsParams, authInfo runtime.ClientAuthInfoWriter) (*StatsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats",
		Method:             "GET",
		PathPattern:        "/stats",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsOK), nil

}

/*
StatsAggregate Returns stats for all regions by service

*/
func (a *Client) StatsAggregate(params *StatsAggregateParams, authInfo runtime.ClientAuthInfoWriter) (*StatsAggregateOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsAggregateParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats_aggregate",
		Method:             "GET",
		PathPattern:        "/stats/aggregate",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsAggregateReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsAggregateOK), nil

}

/*
StatsField Fetches the specified field from the historical stats for each of your services and groups the results by service ID

*/
func (a *Client) StatsField(params *StatsFieldParams, authInfo runtime.ClientAuthInfoWriter) (*StatsFieldOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsFieldParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats_field",
		Method:             "GET",
		PathPattern:        "/stats/field/{field}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsFieldReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsFieldOK), nil

}

/*
StatsRegions Returns list of valid regions

*/
func (a *Client) StatsRegions(params *StatsRegionsParams, authInfo runtime.ClientAuthInfoWriter) (*StatsRegionsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsRegionsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats_regions",
		Method:             "GET",
		PathPattern:        "/stats/regions",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsRegionsReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsRegionsOK), nil

}

/*
StatsService Fetches historical stats for a given service

*/
func (a *Client) StatsService(params *StatsServiceParams, authInfo runtime.ClientAuthInfoWriter) (*StatsServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsServiceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats_service",
		Method:             "GET",
		PathPattern:        "/stats/service/{serviceId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsServiceReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsServiceOK), nil

}

/*
StatsUsage Get aggregated usage data for authenticated user across all Fastly services grouped by region

*/
func (a *Client) StatsUsage(params *StatsUsageParams, authInfo runtime.ClientAuthInfoWriter) (*StatsUsageOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsUsageParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats_usage",
		Method:             "GET",
		PathPattern:        "/stats/usage",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsUsageReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsUsageOK), nil

}

/*
StatsUsageService Returns usage information aggregated by service and grouped by service and region

*/
func (a *Client) StatsUsageService(params *StatsUsageServiceParams, authInfo runtime.ClientAuthInfoWriter) (*StatsUsageServiceOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewStatsUsageServiceParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "stats_usage_service",
		Method:             "GET",
		PathPattern:        "/stats/usage_by_service",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{""},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &StatsUsageServiceReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*StatsUsageServiceOK), nil

}

/*
UploadVcl Upload a `VCL` for a particular service and version
Required form data of **name**
Required form data of **content**

*/
func (a *Client) UploadVcl(params *UploadVclParams, authInfo runtime.ClientAuthInfoWriter) (*UploadVclOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewUploadVclParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "upload_vcl",
		Method:             "POST",
		PathPattern:        "/service/{serviceId}/version/{versionId}/vcl",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/x-www-form-urlencoded"},
		Schemes:            []string{"https"},
		Params:             params,
		Reader:             &UploadVclReader{formats: a.formats},
		AuthInfo:           authInfo,
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	return result.(*UploadVclOK), nil

}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
