package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// DeleteConditionReader is a Reader for the DeleteCondition structure.
type DeleteConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteConditionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteConditionOK creates a DeleteConditionOK with default headers values
func NewDeleteConditionOK() *DeleteConditionOK {
	return &DeleteConditionOK{}
}

/*DeleteConditionOK handles this case with default header values.

Successful response
*/
type DeleteConditionOK struct {
	Payload DeleteConditionOKBody
}

func (o *DeleteConditionOK) Error() string {
	return fmt.Sprintf("[DELETE /service/{serviceId}/version/{versionId}/condition/{name}][%d] deleteConditionOK  %+v", 200, o.Payload)
}

func (o *DeleteConditionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteConditionOKBody delete condition o k body
swagger:model DeleteConditionOKBody
*/
type DeleteConditionOKBody interface{}
