package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteConditionParams creates a new DeleteConditionParams object
// with the default values initialized.
func NewDeleteConditionParams() *DeleteConditionParams {
	var ()
	return &DeleteConditionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteConditionParamsWithTimeout creates a new DeleteConditionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteConditionParamsWithTimeout(timeout time.Duration) *DeleteConditionParams {
	var ()
	return &DeleteConditionParams{

		timeout: timeout,
	}
}

// NewDeleteConditionParamsWithContext creates a new DeleteConditionParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteConditionParamsWithContext(ctx context.Context) *DeleteConditionParams {
	var ()
	return &DeleteConditionParams{

		Context: ctx,
	}
}

/*DeleteConditionParams contains all the parameters to send to the API endpoint
for the delete condition operation typically these are written to a http.Request
*/
type DeleteConditionParams struct {

	/*Name
	  Name of the condition

	*/
	Name string
	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete condition params
func (o *DeleteConditionParams) WithTimeout(timeout time.Duration) *DeleteConditionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete condition params
func (o *DeleteConditionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete condition params
func (o *DeleteConditionParams) WithContext(ctx context.Context) *DeleteConditionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete condition params
func (o *DeleteConditionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithName adds the name to the delete condition params
func (o *DeleteConditionParams) WithName(name string) *DeleteConditionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete condition params
func (o *DeleteConditionParams) SetName(name string) {
	o.Name = name
}

// WithServiceID adds the serviceID to the delete condition params
func (o *DeleteConditionParams) WithServiceID(serviceID string) *DeleteConditionParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the delete condition params
func (o *DeleteConditionParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the delete condition params
func (o *DeleteConditionParams) WithVersionID(versionID string) *DeleteConditionParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the delete condition params
func (o *DeleteConditionParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteConditionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
