package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetDomainsParams creates a new GetDomainsParams object
// with the default values initialized.
func NewGetDomainsParams() *GetDomainsParams {
	var ()
	return &GetDomainsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetDomainsParamsWithTimeout creates a new GetDomainsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetDomainsParamsWithTimeout(timeout time.Duration) *GetDomainsParams {
	var ()
	return &GetDomainsParams{

		timeout: timeout,
	}
}

// NewGetDomainsParamsWithContext creates a new GetDomainsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetDomainsParamsWithContext(ctx context.Context) *GetDomainsParams {
	var ()
	return &GetDomainsParams{

		Context: ctx,
	}
}

/*GetDomainsParams contains all the parameters to send to the API endpoint
for the get domains operation typically these are written to a http.Request
*/
type GetDomainsParams struct {

	/*FilterActive
	  Optional parameter for filtering by active service versions

	*/
	FilterActive *bool
	/*FilterServiceID
	  Optional parameter for filtering by service id

	*/
	FilterServiceID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get domains params
func (o *GetDomainsParams) WithTimeout(timeout time.Duration) *GetDomainsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get domains params
func (o *GetDomainsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get domains params
func (o *GetDomainsParams) WithContext(ctx context.Context) *GetDomainsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get domains params
func (o *GetDomainsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithFilterActive adds the filterActive to the get domains params
func (o *GetDomainsParams) WithFilterActive(filterActive *bool) *GetDomainsParams {
	o.SetFilterActive(filterActive)
	return o
}

// SetFilterActive adds the filterActive to the get domains params
func (o *GetDomainsParams) SetFilterActive(filterActive *bool) {
	o.FilterActive = filterActive
}

// WithFilterServiceID adds the filterServiceID to the get domains params
func (o *GetDomainsParams) WithFilterServiceID(filterServiceID *string) *GetDomainsParams {
	o.SetFilterServiceID(filterServiceID)
	return o
}

// SetFilterServiceID adds the filterServiceId to the get domains params
func (o *GetDomainsParams) SetFilterServiceID(filterServiceID *string) {
	o.FilterServiceID = filterServiceID
}

// WriteToRequest writes these params to a swagger request
func (o *GetDomainsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.FilterActive != nil {

		// query param filter[active]
		var qrFilterActive bool
		if o.FilterActive != nil {
			qrFilterActive = *o.FilterActive
		}
		qFilterActive := swag.FormatBool(qrFilterActive)
		if qFilterActive != "" {
			if err := r.SetQueryParam("filter[active]", qFilterActive); err != nil {
				return err
			}
		}

	}

	if o.FilterServiceID != nil {

		// query param filter[service_id]
		var qrFilterServiceID string
		if o.FilterServiceID != nil {
			qrFilterServiceID = *o.FilterServiceID
		}
		qFilterServiceID := qrFilterServiceID
		if qFilterServiceID != "" {
			if err := r.SetQueryParam("filter[service_id]", qFilterServiceID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
