package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetConditionParams creates a new GetConditionParams object
// with the default values initialized.
func NewGetConditionParams() *GetConditionParams {
	var ()
	return &GetConditionParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetConditionParamsWithTimeout creates a new GetConditionParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetConditionParamsWithTimeout(timeout time.Duration) *GetConditionParams {
	var ()
	return &GetConditionParams{

		timeout: timeout,
	}
}

// NewGetConditionParamsWithContext creates a new GetConditionParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetConditionParamsWithContext(ctx context.Context) *GetConditionParams {
	var ()
	return &GetConditionParams{

		Context: ctx,
	}
}

/*GetConditionParams contains all the parameters to send to the API endpoint
for the get condition operation typically these are written to a http.Request
*/
type GetConditionParams struct {

	/*Name
	  Name of the condition

	*/
	Name string
	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get condition params
func (o *GetConditionParams) WithTimeout(timeout time.Duration) *GetConditionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get condition params
func (o *GetConditionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get condition params
func (o *GetConditionParams) WithContext(ctx context.Context) *GetConditionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get condition params
func (o *GetConditionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithName adds the name to the get condition params
func (o *GetConditionParams) WithName(name string) *GetConditionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get condition params
func (o *GetConditionParams) SetName(name string) {
	o.Name = name
}

// WithServiceID adds the serviceID to the get condition params
func (o *GetConditionParams) WithServiceID(serviceID string) *GetConditionParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the get condition params
func (o *GetConditionParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the get condition params
func (o *GetConditionParams) WithVersionID(versionID string) *GetConditionParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the get condition params
func (o *GetConditionParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *GetConditionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
