package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// GetConditionReader is a Reader for the GetCondition structure.
type GetConditionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetConditionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetConditionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetConditionOK creates a GetConditionOK with default headers values
func NewGetConditionOK() *GetConditionOK {
	return &GetConditionOK{}
}

/*GetConditionOK handles this case with default header values.

Successful response
*/
type GetConditionOK struct {
	Payload *models.Condition
}

func (o *GetConditionOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version/{versionId}/condition/{name}][%d] getConditionOK  %+v", 200, o.Payload)
}

func (o *GetConditionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Condition)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
