package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetServicesParams creates a new GetServicesParams object
// with the default values initialized.
func NewGetServicesParams() *GetServicesParams {
	var ()
	return &GetServicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetServicesParamsWithTimeout creates a new GetServicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetServicesParamsWithTimeout(timeout time.Duration) *GetServicesParams {
	var ()
	return &GetServicesParams{

		timeout: timeout,
	}
}

// NewGetServicesParamsWithContext creates a new GetServicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetServicesParamsWithContext(ctx context.Context) *GetServicesParams {
	var ()
	return &GetServicesParams{

		Context: ctx,
	}
}

/*GetServicesParams contains all the parameters to send to the API endpoint
for the get services operation typically these are written to a http.Request
*/
type GetServicesParams struct {

	/*FilterCustomerID
	  Optional parameter for filtering by customer id

	*/
	FilterCustomerID *string
	/*FilterID
	  Optional parameter for filtering by service id

	*/
	FilterID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get services params
func (o *GetServicesParams) WithTimeout(timeout time.Duration) *GetServicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get services params
func (o *GetServicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get services params
func (o *GetServicesParams) WithContext(ctx context.Context) *GetServicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get services params
func (o *GetServicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithFilterCustomerID adds the filterCustomerID to the get services params
func (o *GetServicesParams) WithFilterCustomerID(filterCustomerID *string) *GetServicesParams {
	o.SetFilterCustomerID(filterCustomerID)
	return o
}

// SetFilterCustomerID adds the filterCustomerId to the get services params
func (o *GetServicesParams) SetFilterCustomerID(filterCustomerID *string) {
	o.FilterCustomerID = filterCustomerID
}

// WithFilterID adds the filterID to the get services params
func (o *GetServicesParams) WithFilterID(filterID *string) *GetServicesParams {
	o.SetFilterID(filterID)
	return o
}

// SetFilterID adds the filterId to the get services params
func (o *GetServicesParams) SetFilterID(filterID *string) {
	o.FilterID = filterID
}

// WriteToRequest writes these params to a swagger request
func (o *GetServicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.FilterCustomerID != nil {

		// query param filter[customer_id]
		var qrFilterCustomerID string
		if o.FilterCustomerID != nil {
			qrFilterCustomerID = *o.FilterCustomerID
		}
		qFilterCustomerID := qrFilterCustomerID
		if qFilterCustomerID != "" {
			if err := r.SetQueryParam("filter[customer_id]", qFilterCustomerID); err != nil {
				return err
			}
		}

	}

	if o.FilterID != nil {

		// query param filter[id]
		var qrFilterID string
		if o.FilterID != nil {
			qrFilterID = *o.FilterID
		}
		qFilterID := qrFilterID
		if qFilterID != "" {
			if err := r.SetQueryParam("filter[id]", qFilterID); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
