package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewListConditionsParams creates a new ListConditionsParams object
// with the default values initialized.
func NewListConditionsParams() *ListConditionsParams {
	var ()
	return &ListConditionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewListConditionsParamsWithTimeout creates a new ListConditionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewListConditionsParamsWithTimeout(timeout time.Duration) *ListConditionsParams {
	var ()
	return &ListConditionsParams{

		timeout: timeout,
	}
}

// NewListConditionsParamsWithContext creates a new ListConditionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewListConditionsParamsWithContext(ctx context.Context) *ListConditionsParams {
	var ()
	return &ListConditionsParams{

		Context: ctx,
	}
}

/*ListConditionsParams contains all the parameters to send to the API endpoint
for the list conditions operation typically these are written to a http.Request
*/
type ListConditionsParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the list conditions params
func (o *ListConditionsParams) WithTimeout(timeout time.Duration) *ListConditionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list conditions params
func (o *ListConditionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list conditions params
func (o *ListConditionsParams) WithContext(ctx context.Context) *ListConditionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list conditions params
func (o *ListConditionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the list conditions params
func (o *ListConditionsParams) WithServiceID(serviceID string) *ListConditionsParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the list conditions params
func (o *ListConditionsParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the list conditions params
func (o *ListConditionsParams) WithVersionID(versionID string) *ListConditionsParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the list conditions params
func (o *ListConditionsParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *ListConditionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
