package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// ListConditionsReader is a Reader for the ListConditions structure.
type ListConditionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ListConditionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewListConditionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewListConditionsOK creates a ListConditionsOK with default headers values
func NewListConditionsOK() *ListConditionsOK {
	return &ListConditionsOK{}
}

/*ListConditionsOK handles this case with default header values.

Successful response
*/
type ListConditionsOK struct {
	Payload []*models.Condition
}

func (o *ListConditionsOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version/{versionId}/condition][%d] listConditionsOK  %+v", 200, o.Payload)
}

func (o *ListConditionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
