package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServiceVersionVclsParams creates a new ServiceVersionVclsParams object
// with the default values initialized.
func NewServiceVersionVclsParams() *ServiceVersionVclsParams {
	var ()
	return &ServiceVersionVclsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceVersionVclsParamsWithTimeout creates a new ServiceVersionVclsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceVersionVclsParamsWithTimeout(timeout time.Duration) *ServiceVersionVclsParams {
	var ()
	return &ServiceVersionVclsParams{

		timeout: timeout,
	}
}

// NewServiceVersionVclsParamsWithContext creates a new ServiceVersionVclsParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceVersionVclsParamsWithContext(ctx context.Context) *ServiceVersionVclsParams {
	var ()
	return &ServiceVersionVclsParams{

		Context: ctx,
	}
}

/*ServiceVersionVclsParams contains all the parameters to send to the API endpoint
for the service version vcls operation typically these are written to a http.Request
*/
type ServiceVersionVclsParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service version vcls params
func (o *ServiceVersionVclsParams) WithTimeout(timeout time.Duration) *ServiceVersionVclsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service version vcls params
func (o *ServiceVersionVclsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service version vcls params
func (o *ServiceVersionVclsParams) WithContext(ctx context.Context) *ServiceVersionVclsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service version vcls params
func (o *ServiceVersionVclsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the service version vcls params
func (o *ServiceVersionVclsParams) WithServiceID(serviceID string) *ServiceVersionVclsParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the service version vcls params
func (o *ServiceVersionVclsParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the service version vcls params
func (o *ServiceVersionVclsParams) WithVersionID(versionID string) *ServiceVersionVclsParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the service version vcls params
func (o *ServiceVersionVclsParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceVersionVclsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
