package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServiceVersionsParams creates a new ServiceVersionsParams object
// with the default values initialized.
func NewServiceVersionsParams() *ServiceVersionsParams {
	var ()
	return &ServiceVersionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceVersionsParamsWithTimeout creates a new ServiceVersionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceVersionsParamsWithTimeout(timeout time.Duration) *ServiceVersionsParams {
	var ()
	return &ServiceVersionsParams{

		timeout: timeout,
	}
}

// NewServiceVersionsParamsWithContext creates a new ServiceVersionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceVersionsParamsWithContext(ctx context.Context) *ServiceVersionsParams {
	var ()
	return &ServiceVersionsParams{

		Context: ctx,
	}
}

/*ServiceVersionsParams contains all the parameters to send to the API endpoint
for the service versions operation typically these are written to a http.Request
*/
type ServiceVersionsParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service versions params
func (o *ServiceVersionsParams) WithTimeout(timeout time.Duration) *ServiceVersionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service versions params
func (o *ServiceVersionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service versions params
func (o *ServiceVersionsParams) WithContext(ctx context.Context) *ServiceVersionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service versions params
func (o *ServiceVersionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the service versions params
func (o *ServiceVersionsParams) WithServiceID(serviceID string) *ServiceVersionsParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the service versions params
func (o *ServiceVersionsParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceVersionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
