package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServiceVersionBoilerplateParams creates a new ServiceVersionBoilerplateParams object
// with the default values initialized.
func NewServiceVersionBoilerplateParams() *ServiceVersionBoilerplateParams {
	var ()
	return &ServiceVersionBoilerplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceVersionBoilerplateParamsWithTimeout creates a new ServiceVersionBoilerplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceVersionBoilerplateParamsWithTimeout(timeout time.Duration) *ServiceVersionBoilerplateParams {
	var ()
	return &ServiceVersionBoilerplateParams{

		timeout: timeout,
	}
}

// NewServiceVersionBoilerplateParamsWithContext creates a new ServiceVersionBoilerplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceVersionBoilerplateParamsWithContext(ctx context.Context) *ServiceVersionBoilerplateParams {
	var ()
	return &ServiceVersionBoilerplateParams{

		Context: ctx,
	}
}

/*ServiceVersionBoilerplateParams contains all the parameters to send to the API endpoint
for the service version boilerplate operation typically these are written to a http.Request
*/
type ServiceVersionBoilerplateParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) WithTimeout(timeout time.Duration) *ServiceVersionBoilerplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) WithContext(ctx context.Context) *ServiceVersionBoilerplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) WithServiceID(serviceID string) *ServiceVersionBoilerplateParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) WithVersionID(versionID string) *ServiceVersionBoilerplateParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the service version boilerplate params
func (o *ServiceVersionBoilerplateParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceVersionBoilerplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
