package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewServiceVersionGeneratedVclParams creates a new ServiceVersionGeneratedVclParams object
// with the default values initialized.
func NewServiceVersionGeneratedVclParams() *ServiceVersionGeneratedVclParams {
	var ()
	return &ServiceVersionGeneratedVclParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewServiceVersionGeneratedVclParamsWithTimeout creates a new ServiceVersionGeneratedVclParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewServiceVersionGeneratedVclParamsWithTimeout(timeout time.Duration) *ServiceVersionGeneratedVclParams {
	var ()
	return &ServiceVersionGeneratedVclParams{

		timeout: timeout,
	}
}

// NewServiceVersionGeneratedVclParamsWithContext creates a new ServiceVersionGeneratedVclParams object
// with the default values initialized, and the ability to set a context for a request
func NewServiceVersionGeneratedVclParamsWithContext(ctx context.Context) *ServiceVersionGeneratedVclParams {
	var ()
	return &ServiceVersionGeneratedVclParams{

		Context: ctx,
	}
}

/*ServiceVersionGeneratedVclParams contains all the parameters to send to the API endpoint
for the service version generated vcl operation typically these are written to a http.Request
*/
type ServiceVersionGeneratedVclParams struct {

	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) WithTimeout(timeout time.Duration) *ServiceVersionGeneratedVclParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) WithContext(ctx context.Context) *ServiceVersionGeneratedVclParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithServiceID adds the serviceID to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) WithServiceID(serviceID string) *ServiceVersionGeneratedVclParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) WithVersionID(versionID string) *ServiceVersionGeneratedVclParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the service version generated vcl params
func (o *ServiceVersionGeneratedVclParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *ServiceVersionGeneratedVclParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
