package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// ServiceVersionVclsReader is a Reader for the ServiceVersionVcls structure.
type ServiceVersionVclsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceVersionVclsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewServiceVersionVclsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServiceVersionVclsOK creates a ServiceVersionVclsOK with default headers values
func NewServiceVersionVclsOK() *ServiceVersionVclsOK {
	return &ServiceVersionVclsOK{}
}

/*ServiceVersionVclsOK handles this case with default header values.

Successful response
*/
type ServiceVersionVclsOK struct {
	Payload []*models.Vcl
}

func (o *ServiceVersionVclsOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version/{versionId}/vcl][%d] serviceVersionVclsOK  %+v", 200, o.Payload)
}

func (o *ServiceVersionVclsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
