package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// ServiceVersionsReader is a Reader for the ServiceVersions structure.
type ServiceVersionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceVersionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewServiceVersionsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServiceVersionsOK creates a ServiceVersionsOK with default headers values
func NewServiceVersionsOK() *ServiceVersionsOK {
	return &ServiceVersionsOK{}
}

/*ServiceVersionsOK handles this case with default header values.

Successful response
*/
type ServiceVersionsOK struct {
	Payload []*models.Version
}

func (o *ServiceVersionsOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version][%d] serviceVersionsOK  %+v", 200, o.Payload)
}

func (o *ServiceVersionsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
