package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// ServiceVersionGeneratedVclReader is a Reader for the ServiceVersionGeneratedVcl structure.
type ServiceVersionGeneratedVclReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceVersionGeneratedVclReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewServiceVersionGeneratedVclOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServiceVersionGeneratedVclOK creates a ServiceVersionGeneratedVclOK with default headers values
func NewServiceVersionGeneratedVclOK() *ServiceVersionGeneratedVclOK {
	return &ServiceVersionGeneratedVclOK{}
}

/*ServiceVersionGeneratedVclOK handles this case with default header values.

Successful response
*/
type ServiceVersionGeneratedVclOK struct {
	Payload *models.Vcl
}

func (o *ServiceVersionGeneratedVclOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version/{versionId}/generated_vcl][%d] serviceVersionGeneratedVclOK  %+v", 200, o.Payload)
}

func (o *ServiceVersionGeneratedVclOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Vcl)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
