package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"
)

// ServiceVersionBoilerplateReader is a Reader for the ServiceVersionBoilerplate structure.
type ServiceVersionBoilerplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ServiceVersionBoilerplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewServiceVersionBoilerplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewServiceVersionBoilerplateOK creates a ServiceVersionBoilerplateOK with default headers values
func NewServiceVersionBoilerplateOK() *ServiceVersionBoilerplateOK {
	return &ServiceVersionBoilerplateOK{}
}

/*ServiceVersionBoilerplateOK handles this case with default header values.

Successful response
*/
type ServiceVersionBoilerplateOK struct {
	Payload string
}

func (o *ServiceVersionBoilerplateOK) Error() string {
	return fmt.Sprintf("[GET /service/{serviceId}/version/{versionId}/boilerplate][%d] serviceVersionBoilerplateOK  %+v", 200, o.Payload)
}

func (o *ServiceVersionBoilerplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
