package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStatsRegionsParams creates a new StatsRegionsParams object
// with the default values initialized.
func NewStatsRegionsParams() *StatsRegionsParams {

	return &StatsRegionsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStatsRegionsParamsWithTimeout creates a new StatsRegionsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStatsRegionsParamsWithTimeout(timeout time.Duration) *StatsRegionsParams {

	return &StatsRegionsParams{

		timeout: timeout,
	}
}

// NewStatsRegionsParamsWithContext creates a new StatsRegionsParams object
// with the default values initialized, and the ability to set a context for a request
func NewStatsRegionsParamsWithContext(ctx context.Context) *StatsRegionsParams {

	return &StatsRegionsParams{

		Context: ctx,
	}
}

/*StatsRegionsParams contains all the parameters to send to the API endpoint
for the stats regions operation typically these are written to a http.Request
*/
type StatsRegionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stats regions params
func (o *StatsRegionsParams) WithTimeout(timeout time.Duration) *StatsRegionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stats regions params
func (o *StatsRegionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stats regions params
func (o *StatsRegionsParams) WithContext(ctx context.Context) *StatsRegionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stats regions params
func (o *StatsRegionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *StatsRegionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
