package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// StatsReader is a Reader for the Stats structure.
type StatsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStatsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStatsOK creates a StatsOK with default headers values
func NewStatsOK() *StatsOK {
	return &StatsOK{}
}

/*StatsOK handles this case with default header values.

Successful response
*/
type StatsOK struct {
	Payload *models.Stats
}

func (o *StatsOK) Error() string {
	return fmt.Sprintf("[GET /stats][%d] statsOK  %+v", 200, o.Payload)
}

func (o *StatsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Stats)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
