package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// StatsUsageServiceReader is a Reader for the StatsUsageService structure.
type StatsUsageServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatsUsageServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStatsUsageServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStatsUsageServiceOK creates a StatsUsageServiceOK with default headers values
func NewStatsUsageServiceOK() *StatsUsageServiceOK {
	return &StatsUsageServiceOK{}
}

/*StatsUsageServiceOK handles this case with default header values.

Successful response
*/
type StatsUsageServiceOK struct {
	Payload *models.Stats
}

func (o *StatsUsageServiceOK) Error() string {
	return fmt.Sprintf("[GET /stats/usage_by_service][%d] statsUsageServiceOK  %+v", 200, o.Payload)
}

func (o *StatsUsageServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Stats)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
