package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// StatsUsageReader is a Reader for the StatsUsage structure.
type StatsUsageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatsUsageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStatsUsageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStatsUsageOK creates a StatsUsageOK with default headers values
func NewStatsUsageOK() *StatsUsageOK {
	return &StatsUsageOK{}
}

/*StatsUsageOK handles this case with default header values.

Successful response
*/
type StatsUsageOK struct {
	Payload *models.StatsUsage
}

func (o *StatsUsageOK) Error() string {
	return fmt.Sprintf("[GET /stats/usage][%d] statsUsageOK  %+v", 200, o.Payload)
}

func (o *StatsUsageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.StatsUsage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
