package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// StatsFieldReader is a Reader for the StatsField structure.
type StatsFieldReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *StatsFieldReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewStatsFieldOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewStatsFieldOK creates a StatsFieldOK with default headers values
func NewStatsFieldOK() *StatsFieldOK {
	return &StatsFieldOK{}
}

/*StatsFieldOK handles this case with default header values.

Successful response
*/
type StatsFieldOK struct {
	Payload *models.Stats
}

func (o *StatsFieldOK) Error() string {
	return fmt.Sprintf("[GET /stats/field/{field}][%d] statsFieldOK  %+v", 200, o.Payload)
}

func (o *StatsFieldOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Stats)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
