package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStatsServiceParams creates a new StatsServiceParams object
// with the default values initialized.
func NewStatsServiceParams() *StatsServiceParams {
	var ()
	return &StatsServiceParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStatsServiceParamsWithTimeout creates a new StatsServiceParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStatsServiceParamsWithTimeout(timeout time.Duration) *StatsServiceParams {
	var ()
	return &StatsServiceParams{

		timeout: timeout,
	}
}

// NewStatsServiceParamsWithContext creates a new StatsServiceParams object
// with the default values initialized, and the ability to set a context for a request
func NewStatsServiceParamsWithContext(ctx context.Context) *StatsServiceParams {
	var ()
	return &StatsServiceParams{

		Context: ctx,
	}
}

/*StatsServiceParams contains all the parameters to send to the API endpoint
for the stats service operation typically these are written to a http.Request
*/
type StatsServiceParams struct {

	/*By
	  Sampling rate (minute|hour|day)

	*/
	By *string
	/*From
	  Beginning of time window. Inclusive.

	*/
	From *string
	/*Region
	  Name of region

	*/
	Region *string
	/*ServiceID
	  Id of service

	*/
	ServiceID string
	/*To
	  End of time window. Exclusive.

	*/
	To *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stats service params
func (o *StatsServiceParams) WithTimeout(timeout time.Duration) *StatsServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stats service params
func (o *StatsServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stats service params
func (o *StatsServiceParams) WithContext(ctx context.Context) *StatsServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stats service params
func (o *StatsServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBy adds the by to the stats service params
func (o *StatsServiceParams) WithBy(by *string) *StatsServiceParams {
	o.SetBy(by)
	return o
}

// SetBy adds the by to the stats service params
func (o *StatsServiceParams) SetBy(by *string) {
	o.By = by
}

// WithFrom adds the from to the stats service params
func (o *StatsServiceParams) WithFrom(from *string) *StatsServiceParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the stats service params
func (o *StatsServiceParams) SetFrom(from *string) {
	o.From = from
}

// WithRegion adds the region to the stats service params
func (o *StatsServiceParams) WithRegion(region *string) *StatsServiceParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the stats service params
func (o *StatsServiceParams) SetRegion(region *string) {
	o.Region = region
}

// WithServiceID adds the serviceID to the stats service params
func (o *StatsServiceParams) WithServiceID(serviceID string) *StatsServiceParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the stats service params
func (o *StatsServiceParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithTo adds the to to the stats service params
func (o *StatsServiceParams) WithTo(to *string) *StatsServiceParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the stats service params
func (o *StatsServiceParams) SetTo(to *string) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *StatsServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.By != nil {

		// query param by
		var qrBy string
		if o.By != nil {
			qrBy = *o.By
		}
		qBy := qrBy
		if qBy != "" {
			if err := r.SetQueryParam("by", qBy); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom string
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.Region != nil {

		// query param region
		var qrRegion string
		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {
			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}

	}

	// path param service_id
	if err := r.SetPathParam("service_id", o.ServiceID); err != nil {
		return err
	}

	if o.To != nil {

		// query param to
		var qrTo string
		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {
			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
