package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewStatsAggregateParams creates a new StatsAggregateParams object
// with the default values initialized.
func NewStatsAggregateParams() *StatsAggregateParams {
	var ()
	return &StatsAggregateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewStatsAggregateParamsWithTimeout creates a new StatsAggregateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewStatsAggregateParamsWithTimeout(timeout time.Duration) *StatsAggregateParams {
	var ()
	return &StatsAggregateParams{

		timeout: timeout,
	}
}

// NewStatsAggregateParamsWithContext creates a new StatsAggregateParams object
// with the default values initialized, and the ability to set a context for a request
func NewStatsAggregateParamsWithContext(ctx context.Context) *StatsAggregateParams {
	var ()
	return &StatsAggregateParams{

		Context: ctx,
	}
}

/*StatsAggregateParams contains all the parameters to send to the API endpoint
for the stats aggregate operation typically these are written to a http.Request
*/
type StatsAggregateParams struct {

	/*By
	  Sampling rate (minute|hour|day)

	*/
	By *string
	/*From
	  Beginning of time window. Inclusive.

	*/
	From *string
	/*Region
	  Name of region

	*/
	Region *string
	/*To
	  End of time window. Exclusive.

	*/
	To *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the stats aggregate params
func (o *StatsAggregateParams) WithTimeout(timeout time.Duration) *StatsAggregateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the stats aggregate params
func (o *StatsAggregateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the stats aggregate params
func (o *StatsAggregateParams) WithContext(ctx context.Context) *StatsAggregateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the stats aggregate params
func (o *StatsAggregateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBy adds the by to the stats aggregate params
func (o *StatsAggregateParams) WithBy(by *string) *StatsAggregateParams {
	o.SetBy(by)
	return o
}

// SetBy adds the by to the stats aggregate params
func (o *StatsAggregateParams) SetBy(by *string) {
	o.By = by
}

// WithFrom adds the from to the stats aggregate params
func (o *StatsAggregateParams) WithFrom(from *string) *StatsAggregateParams {
	o.SetFrom(from)
	return o
}

// SetFrom adds the from to the stats aggregate params
func (o *StatsAggregateParams) SetFrom(from *string) {
	o.From = from
}

// WithRegion adds the region to the stats aggregate params
func (o *StatsAggregateParams) WithRegion(region *string) *StatsAggregateParams {
	o.SetRegion(region)
	return o
}

// SetRegion adds the region to the stats aggregate params
func (o *StatsAggregateParams) SetRegion(region *string) {
	o.Region = region
}

// WithTo adds the to to the stats aggregate params
func (o *StatsAggregateParams) WithTo(to *string) *StatsAggregateParams {
	o.SetTo(to)
	return o
}

// SetTo adds the to to the stats aggregate params
func (o *StatsAggregateParams) SetTo(to *string) {
	o.To = to
}

// WriteToRequest writes these params to a swagger request
func (o *StatsAggregateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if o.By != nil {

		// query param by
		var qrBy string
		if o.By != nil {
			qrBy = *o.By
		}
		qBy := qrBy
		if qBy != "" {
			if err := r.SetQueryParam("by", qBy); err != nil {
				return err
			}
		}

	}

	if o.From != nil {

		// query param from
		var qrFrom string
		if o.From != nil {
			qrFrom = *o.From
		}
		qFrom := qrFrom
		if qFrom != "" {
			if err := r.SetQueryParam("from", qFrom); err != nil {
				return err
			}
		}

	}

	if o.Region != nil {

		// query param region
		var qrRegion string
		if o.Region != nil {
			qrRegion = *o.Region
		}
		qRegion := qrRegion
		if qRegion != "" {
			if err := r.SetQueryParam("region", qRegion); err != nil {
				return err
			}
		}

	}

	if o.To != nil {

		// query param to
		var qrTo string
		if o.To != nil {
			qrTo = *o.To
		}
		qTo := qrTo
		if qTo != "" {
			if err := r.SetQueryParam("to", qTo); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
