package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/fastly/openapi/clients/go/models"
)

// UploadVclReader is a Reader for the UploadVcl structure.
type UploadVclReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadVclReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewUploadVclOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewUploadVclBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewUploadVclOK creates a UploadVclOK with default headers values
func NewUploadVclOK() *UploadVclOK {
	return &UploadVclOK{}
}

/*UploadVclOK handles this case with default header values.

Successful response
*/
type UploadVclOK struct {
	Payload *models.Vcl
}

func (o *UploadVclOK) Error() string {
	return fmt.Sprintf("[POST /service/{serviceId}/version/{versionId}/vcl][%d] uploadVclOK  %+v", 200, o.Payload)
}

func (o *UploadVclOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Vcl)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadVclBadRequest creates a UploadVclBadRequest with default headers values
func NewUploadVclBadRequest() *UploadVclBadRequest {
	return &UploadVclBadRequest{}
}

/*UploadVclBadRequest handles this case with default header values.

Bad request
*/
type UploadVclBadRequest struct {
	Payload *models.BadRequest
}

func (o *UploadVclBadRequest) Error() string {
	return fmt.Sprintf("[POST /service/{serviceId}/version/{versionId}/vcl][%d] uploadVclBadRequest  %+v", 400, o.Payload)
}

func (o *UploadVclBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.BadRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
