package configuration

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"os"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewUploadVclParams creates a new UploadVclParams object
// with the default values initialized.
func NewUploadVclParams() *UploadVclParams {
	var ()
	return &UploadVclParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewUploadVclParamsWithTimeout creates a new UploadVclParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewUploadVclParamsWithTimeout(timeout time.Duration) *UploadVclParams {
	var ()
	return &UploadVclParams{

		timeout: timeout,
	}
}

// NewUploadVclParamsWithContext creates a new UploadVclParams object
// with the default values initialized, and the ability to set a context for a request
func NewUploadVclParamsWithContext(ctx context.Context) *UploadVclParams {
	var ()
	return &UploadVclParams{

		Context: ctx,
	}
}

/*UploadVclParams contains all the parameters to send to the API endpoint
for the upload vcl operation typically these are written to a http.Request
*/
type UploadVclParams struct {

	/*Content
	  Vcl content

	*/
	Content os.File
	/*Name
	  Name of the vcl

	*/
	Name string
	/*ServiceID
	  Id of the service

	*/
	ServiceID string
	/*VersionID
	  Id of the version

	*/
	VersionID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the upload vcl params
func (o *UploadVclParams) WithTimeout(timeout time.Duration) *UploadVclParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the upload vcl params
func (o *UploadVclParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the upload vcl params
func (o *UploadVclParams) WithContext(ctx context.Context) *UploadVclParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the upload vcl params
func (o *UploadVclParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithContent adds the content to the upload vcl params
func (o *UploadVclParams) WithContent(content os.File) *UploadVclParams {
	o.SetContent(content)
	return o
}

// SetContent adds the content to the upload vcl params
func (o *UploadVclParams) SetContent(content os.File) {
	o.Content = content
}

// WithName adds the name to the upload vcl params
func (o *UploadVclParams) WithName(name string) *UploadVclParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the upload vcl params
func (o *UploadVclParams) SetName(name string) {
	o.Name = name
}

// WithServiceID adds the serviceID to the upload vcl params
func (o *UploadVclParams) WithServiceID(serviceID string) *UploadVclParams {
	o.SetServiceID(serviceID)
	return o
}

// SetServiceID adds the serviceId to the upload vcl params
func (o *UploadVclParams) SetServiceID(serviceID string) {
	o.ServiceID = serviceID
}

// WithVersionID adds the versionID to the upload vcl params
func (o *UploadVclParams) WithVersionID(versionID string) *UploadVclParams {
	o.SetVersionID(versionID)
	return o
}

// SetVersionID adds the versionId to the upload vcl params
func (o *UploadVclParams) SetVersionID(versionID string) {
	o.VersionID = versionID
}

// WriteToRequest writes these params to a swagger request
func (o *UploadVclParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// form file param content
	if err := r.SetFileParam("content", &o.Content); err != nil {
		return err
	}

	// form param name
	frName := o.Name
	fName := frName
	if fName != "" {
		if err := r.SetFormParam("name", fName); err != nil {
			return err
		}
	}

	// path param serviceId
	if err := r.SetPathParam("serviceId", o.ServiceID); err != nil {
		return err
	}

	// path param versionId
	if err := r.SetPathParam("versionId", o.VersionID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
