package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Condition condition
// swagger:model Condition
type Condition struct {

	// The condition comment
	Comment string `json:"comment,omitempty"`

	// The time that this condition was created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The time that this condition was deleted at
	DeletedAt *strfmt.DateTime `json:"deleted_at,omitempty"`

	// The condition name
	Name string `json:"name,omitempty"`

	// The condition priority
	Priority string `json:"priority,omitempty"`

	// The service that this condition belongs to
	ServiceID string `json:"service_id,omitempty"`

	// The condition statement
	Statement string `json:"statement,omitempty"`

	// The condition type
	Type string `json:"type,omitempty"`

	// The time that this condition was last updated
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`

	// The version that this condition belongs to
	Version int64 `json:"version,omitempty"`
}

// Validate validates this condition
func (m *Condition) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
