package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Event event
// swagger:model Event
type Event struct {

	// attributes
	Attributes *EventAttributes `json:"attributes,omitempty"`

	// The ID of the service
	ID string `json:"id,omitempty"`

	// The JSON-API type for a service
	Type string `json:"type,omitempty"`
}

// Validate validates this event
func (m *Event) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttributes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Event) validateAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.Attributes) { // not required
		return nil
	}

	if m.Attributes != nil {

		if err := m.Attributes.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

// EventAttributes The JSON-API object for service attributes
// swagger:model EventAttributes
type EventAttributes struct {

	// Whether the event was created by a Fastly admin
	Admin bool `json:"admin,omitempty"`

	// The time that this event was created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The customer that the event belongs to
	CustomerID string `json:"customer_id,omitempty"`

	// Human-readable event description
	Description string `json:"description,omitempty"`

	// Computer-readable type of the event
	EventType string `json:"event_type,omitempty"`

	// The IP address that initiated the event
	IP string `json:"ip,omitempty"`

	// Additional metadata about the event
	Metadata interface{} `json:"metadata,omitempty"`

	// The service relating to this event
	ServiceID string `json:"service_id,omitempty"`

	// The id of the user that initiated this event
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this event attributes
func (m *EventAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
