package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Feature feature
// swagger:model Feature
type Feature struct {

	// attributes
	Attributes *FeatureAttributes `json:"attributes,omitempty"`

	// The ID of the feature
	ID string `json:"id,omitempty"`

	// The JSON-API type for a feature
	Type *string `json:"type,omitempty"`
}

// Validate validates this feature
func (m *Feature) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttributes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Feature) validateAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.Attributes) { // not required
		return nil
	}

	if m.Attributes != nil {

		if err := m.Attributes.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

// FeatureAttributes feature attributes
// swagger:model FeatureAttributes
type FeatureAttributes struct {

	// Describes who can enable this feature. One of: private, protected, or public.
	Availability *string `json:"availability,omitempty"`

	// Whether the feature is enabled globally
	Enabled *bool `json:"enabled,omitempty"`

	// The name of the feature
	Name string `json:"name,omitempty"`
}

// Validate validates this feature attributes
func (m *FeatureAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
