package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/go-openapi/errors"
)

// Service service
// swagger:model Service
type Service struct {

	// attributes
	Attributes *ServiceAttributes `json:"attributes,omitempty"`

	// The ID of the service
	ID string `json:"id,omitempty"`

	// The JSON-API type for a service
	Type string `json:"type,omitempty"`
}

// Validate validates this service
func (m *Service) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAttributes(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Service) validateAttributes(formats strfmt.Registry) error {

	if swag.IsZero(m.Attributes) { // not required
		return nil
	}

	if m.Attributes != nil {

		if err := m.Attributes.Validate(formats); err != nil {
			return err
		}
	}

	return nil
}

// ServiceAttributes The JSON-API object for service attributes
// swagger:model ServiceAttributes
type ServiceAttributes struct {

	// The active version of the service
	ActiveVersion int64 `json:"active_version,omitempty"`

	// A comment field for a service
	Comment string `json:"comment,omitempty"`

	// The time that this service was created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The customer that the service belongs to
	CustomerID string `json:"customer_id,omitempty"`

	// The time that this service was deleted at
	DeletedAt *strfmt.DateTime `json:"deleted_at,omitempty"`

	// The name of the service
	Name string `json:"name,omitempty"`

	// The time that this service was last updated
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this service attributes
func (m *ServiceAttributes) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
