package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// StatsUsage stats usage
// swagger:model StatsUsage
type StatsUsage struct {

	// Data payload
	Data interface{} `json:"data,omitempty"`

	// Paramaters used to generate these stats
	Meta interface{} `json:"meta,omitempty"`

	// Error message if applicable
	Msg string `json:"msg,omitempty"`

	// Status of stats request (success|failure)
	Status string `json:"status,omitempty"`
}

// Validate validates this stats usage
func (m *StatsUsage) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
