package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Token token
// swagger:model Token
type Token struct {

	// The credential to use in the Fastly-Key header.
	AccessToken string `json:"access_token,omitempty"`

	// The time that the token was created at.
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The time that the token expires at if provided.
	ExpiresAt *strfmt.DateTime `json:"expires_at,omitempty"`

	// The ID of the Token
	ID string `json:"id,omitempty"`

	// The name of the token if provided.
	Name string `json:"name,omitempty"`

	// The Token scopes if proided.
	Scope string `json:"scope,omitempty"`

	// The ID of the Service if provided.
	ServiceID string `json:"service_id,omitempty"`

	// The ID of the User that the token belongs to.
	UserID string `json:"user_id,omitempty"`
}

// Validate validates this token
func (m *Token) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
