package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// User user
// swagger:model User
type User struct {

	// The ID of the Customer the User is a member of
	CustomerID string `json:"customer_id,omitempty"`

	// The ID of the User
	ID string `json:"id,omitempty"`

	// The login name (email address) of the User
	Login string `json:"login,omitempty"`

	// The full name of the User
	Name string `json:"name,omitempty"`

	// The role of the User
	Role string `json:"role,omitempty"`
}

// Validate validates this user
func (m *User) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
