package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Vcl vcl
// swagger:model Vcl
type Vcl struct {

	// Content of the vcl
	Content string `json:"content,omitempty"`

	// Main VCL
	Main bool `json:"main,omitempty"`

	// Name of the VCL
	Name string `json:"name,omitempty"`

	// The ID of the Service the vcl belongs to
	ServiceID string `json:"service_id,omitempty"`

	// The version the vcl belongs to
	Version int64 `json:"version,omitempty"`
}

// Validate validates this vcl
func (m *Vcl) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
