package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// Version version
// swagger:model Version
type Version struct {

	// This is the active version
	Active bool `json:"active,omitempty"`

	// Comment field
	Comment string `json:"comment,omitempty"`

	// The time that this service was created at
	CreatedAt strfmt.DateTime `json:"created_at,omitempty"`

	// The time that this service was deleted at
	DeletedAt *strfmt.DateTime `json:"deleted_at,omitempty"`

	// Version is deployed
	Deployed bool `json:"deployed,omitempty"`

	// Version is locked
	Locked bool `json:"locked,omitempty"`

	// Version number
	Number int64 `json:"number,omitempty"`

	// Id of the service
	ServiceID string `json:"service_id,omitempty"`

	// Version in staging
	Staging bool `json:"staging,omitempty"`

	// Version in testing
	Testing bool `json:"testing,omitempty"`

	// The time that this service was last updated
	UpdatedAt strfmt.DateTime `json:"updated_at,omitempty"`
}

// Validate validates this version
func (m *Version) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
